---

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags: tools

- name: install git
  apt: pkg=git state=present

- name: install build-essential
  apt: pkg=build-essential state=present

- name: install popstgresql & tools
  apt: name={{item}} state=present
  with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
