---

- name: ensure apt cache is up to date
  apt: update_cache=yes cache_valid_time=3600

- name: ensure packages are installed
  apt: name={{item}} state=present
  with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

#- name: ensure database is created
#  postgresql_db: name={{ zabbix_database_name }}
#  become_user: postgres
#
#- name: ensure user has access to database
#  postgresql_user: db={{ zabbix_database_name }} name={{ zabbix_database_user }} password={{ zabbix_database_password }} priv=ALL
#  become_user: postgres
#
#- name: ensure user does not have unnecessary privilege
#  postgresql_user: name={{ zabbix_database_user }} role_attr_flags=NOSUPERUSER
#  become_user: postgres
#
#- name: ensure no other user can access the database
#  postgresql_privs: db={{ zabbix_database_name }} role=PUBLIC type=database priv=ALL state=absent
#  become_user: postgres
